version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: telemedicine_db
    environment:
      POSTGRES_USER: ${DB_USERNAME} # Sẽ lấy từ file .env
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
      PG_DATA: /var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - telemedicine_network
    restart: unless-stopped

  redis:
    image: redis:alpine
    container_name: telemedicine_redis
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data
    networks:
      - telemedicine_network
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:

networks:
  telemedicine_network:
    driver: bridge
